# Generated by Django 5.2.5 on 2025-09-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='wallet',
        ),
    ]
