# Generated by Django 5.2.5 on 2025-10-04 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0002_initial"),
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawal",
            name="liquidity",
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="packs.pack",
            ),
        ),
        migrations.AddField(
            model_name="withdrawal",
            name="sum",
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True),
        ),
    ]
