# Generated by Django 5.2.5 on 2025-10-01 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0008_rename_sell_data_packsell_date_remove_packsell_price'),
        ('wallet', '0002_remove_deposit_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='pack',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='liquidity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packs.liquidity'),
        ),
    ]
