# Generated by Django 5.2.5 on 2025-10-13 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packs", "0004_alter_pack_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roulette",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticket_price", models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ("time_to_bet", models.IntegerField(default=30)),
                ("bet_in_ton", models.BooleanField(default=True)),
                ("bet_in_nft", models.BooleanField(default=True)),
                ("ton_fee", models.DecimalField(decimal_places=3, default=0.2, max_digits=5)),
                ("total_bet", models.DecimalField(decimal_places=3, default=0, max_digits=20)),
                ("total_free_tickets", models.BigIntegerField(default=0)),
                ("total_paid_tickets", models.BigIntegerField(default=0)),
                ("total_sum_paid_tickets", models.DecimalField(decimal_places=3, default=0, max_digits=20)),
            ],
            options={
                "db_table": "roulette",
            },
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("is_finished", models.BooleanField(default=False)),
                ("roulette", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rolls.roulette")),
            ],
            options={
                "db_table": "round",
            },
        ),
        migrations.CreateModel(
            name="RoundResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sum", models.DecimalField(decimal_places=3, max_digits=20)),
                ("meta_data", models.JSONField(default=dict)),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rolls.round")),
                ("winner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "round_result",
            },
        ),
        migrations.CreateModel(
            name="NFTBet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "liquidity",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="packs.liquidity"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rolls.round")),
            ],
            options={
                "db_table": "nft_bet",
                "abstract": False,
                "indexes": [models.Index(fields=["round", "user"], name="nft_bet_round_i_d6f0c8_idx")],
            },
        ),
        migrations.CreateModel(
            name="TicketUsage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rolls.round")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "round")},
            },
        ),
        migrations.CreateModel(
            name="TonBet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=20)),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rolls.round")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "ton_bet",
                "abstract": False,
                "indexes": [models.Index(fields=["round", "user"], name="ton_bet_round_i_d4c01a_idx")],
            },
        ),
    ]
