# Generated by Django 5.2.5 on 2025-10-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="is_finished",
        ),
        migrations.AddField(
            model_name="round",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
