# Generated by Django 5.2.5 on 2025-10-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rolls", "0002_remove_round_is_finished_round_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="secret",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="secret_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
