# Generated by Django 5.2.5 on 2025-10-11 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0003_rename_in_case_liquidity_free"),
        ("upgrade", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upgrade",
            name="bet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="upgrade_as_bet", to="packs.pack"
            ),
        ),
        migrations.AlterField(
            model_name="upgrade",
            name="drop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upgrade_as_drop",
                to="packs.pack",
            ),
        ),
    ]
