# Generated by Django 5.2.5 on 2025-10-04 16:46

import cases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("packs", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=3, max_digits=20)),
                ("current_fee", models.FloatField()),
                ("base_fee", models.FloatField(default=20.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("out_of_stickers", "Out of stickers"),
                        ],
                        default=cases.models.CaseStatus["INACTIVE"],
                        max_length=50,
                    ),
                ),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="cases/"),
                ),
            ],
            options={
                "db_table": "Case",
            },
        ),
        migrations.CreateModel(
            name="CaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chance", models.FloatField()),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_item",
                        to="cases.case",
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packs",
                        to="packs.pack",
                    ),
                ),
            ],
            options={
                "db_table": "CaseItem",
            },
        ),
        migrations.CreateModel(
            name="CaseLiquidity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_liquidity",
                        to="cases.case",
                    ),
                ),
                (
                    "liquidity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="packs.liquidity",
                    ),
                ),
            ],
            options={
                "db_table": "CaseLiquidity",
            },
        ),
        migrations.CreateModel(
            name="CaseOpen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "case",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="cases.case"),
                ),
                (
                    "drop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="packs.liquidity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "CaseOpen",
            },
        ),
    ]
