# Generated by Django 5.2.5 on 2025-09-04 13:29

import cases.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('current_fee', models.FloatField()),
                ('base_fee', models.FloatField(default=20.0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stickers', 'Out of stickers')], default=cases.models.CaseStatus['INACTIVE'], max_length=50)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='cases/')),
            ],
        ),
        migrations.CreateModel(
            name='CaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_items', to='cases.case')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='packs.pack')),
            ],
        ),
        migrations.CreateModel(
            name='CaseOpen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_data', models.DateTimeField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('drop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packs.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
