# Generated by Django 5.2.5 on 2025-09-30 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('packs', '0004_liquidity_in_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseopen',
            name='drop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packs.liquidity'),
        ),
        migrations.AlterModelTable(
            name='case',
            table='Case',
        ),
        migrations.AlterModelTable(
            name='caseopen',
            table='CaseOpen',
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chance', models.FloatField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_item', to='cases.case')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='packs.pack')),
            ],
            options={
                'db_table': 'CaseItem',
            },
        ),
        migrations.CreateModel(
            name='CaseLiquidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_liquidity', to='cases.case')),
                ('liquidity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packs.liquidity')),
            ],
            options={
                'db_table': 'CaseLiquidity',
            },
        ),
        migrations.DeleteModel(
            name='CaseItems',
        ),
    ]
