# Generated by Django 5.2.5 on 2025-10-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0001_initial"),
        ("packs", "0004_alter_pack_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="image_url",
            field=models.URLField(
                default="https://stickercasebucket.s3.eu-north-1.amazonaws.com/cases/plug.png", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="caseitem",
            name="pack",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cases", to="packs.pack"),
        ),
    ]
