# Generated by Django 5.2.5 on 2025-09-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_caseopen_drop_alter_case_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseopen',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
