# Generated by Django 5.2.5 on 2025-09-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_caseopen_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseopen',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
