# Generated by Django 5.2.5 on 2025-10-01 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_caseopen_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseopen',
            old_name='open_data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='caseopen',
            name='price',
        ),
    ]
