# Generated by Django 5.2.5 on 2025-10-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image_url",
            field=models.URLField(
                default="https://stickercasebucket.s3.eu-north-1.amazonaws.com/users/plug.png", max_length=500
            ),
        ),
    ]
