# Generated by Django 5.2.5 on 2025-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='wallet_connection',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
