# Generated by Django 5.2.5 on 2025-09-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_withdrawal_user_customuser_wallet_connection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='wallet_connection',
            new_name='wallet_connection_date',
        ),
    ]
