# Generated by Django 5.2.5 on 2025-09-30 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_remove_liquidity_id_liquidity_buy_price_and_more'),
        ('users', '0003_rename_wallet_connection_customuser_wallet_connection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinventory',
            name='pack',
        ),
        migrations.AddField(
            model_name='userinventory',
            name='liquidity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packs.liquidity'),
        ),
        migrations.AlterModelTable(
            name='userinventory',
            table='UserInventory',
        ),
    ]
