# Generated by Django 5.2.5 on 2025-10-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tickets",
            field=models.IntegerField(default=0),
        ),
    ]
