# Generated by Django 5.2.5 on 2025-09-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userinventory_pack_userinventory_liquidity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='User',
        ),
    ]
