# Generated by Django 5.2.5 on 2025-10-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
