# Generated by Django 5.2.5 on 2025-11-01 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("pack_name", models.CharField(max_length=255)),
                ("collection_name", models.CharField(max_length=255)),
                ("contributor", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "image_url",
                    models.URLField(
                        default="https://stickercasebucket.s3.eu-north-1.amazonaws.com/packs/plug.png", max_length=500
                    ),
                ),
            ],
            options={
                "db_table": "Pack",
            },
        ),
        migrations.CreateModel(
            name="Liquidity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.IntegerField()),
                ("nft_address", models.TextField()),
                ("link", models.URLField(default="https://getgems.io/")),
                ("free", models.BooleanField(default=True)),
                ("pack", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packs.pack")),
            ],
            options={
                "db_table": "Liquidity",
            },
        ),
        migrations.CreateModel(
            name="PackSell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateTimeField()),
                (
                    "liquidity",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="packs.liquidity"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "PackSell",
            },
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "liquidity",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="packs.liquidity"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "UserInventory",
            },
        ),
    ]
