# Generated by Django 5.2.5 on 2025-09-04 13:28

import packs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=255)),
                ('collection_name', models.CharField(max_length=255)),
                ('contributor', models.CharField(max_length=255)),
                ('floor_price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('status', models.CharField(choices=[('in_stock', 'In stock'), ('out_of_stock', 'Out of stock')], default=packs.models.PackStatus['OUT_OF_STOCK'], max_length=50)),
                ('in_stock_count', models.IntegerField(default=0)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='packs/')),
            ],
        ),
    ]
