# Generated by Django 5.2.5 on 2025-11-01 15:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pack",
            name="image_url",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(max_length=500), blank=True, default=list, size=None
            ),
        ),
    ]
