# Generated by Django 5.2.5 on 2025-09-30 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pack',
            table='Pack',
        ),
        migrations.CreateModel(
            name='Liquidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('link', models.TextField(default='https://getgems.io/')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packs.pack')),
            ],
            options={
                'db_table': 'Liquidity',
            },
        ),
    ]
