# Generated by Django 5.2.5 on 2025-10-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="liquidity",
            old_name="in_case",
            new_name="free",
        ),
    ]
