# Generated by Django 5.2.5 on 2025-09-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0002_alter_pack_table_liquidity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidity',
            name='id',
        ),
        migrations.AddField(
            model_name='liquidity',
            name='buy_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liquidity',
            name='liquidity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
