# Generated by Django 5.2.5 on 2025-10-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packs", "0003_rename_in_case_liquidity_free"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pack",
            name="image_url",
            field=models.URLField(
                default="https://stickercasebucket.s3.eu-north-1.amazonaws.com/packs/plug.png", max_length=500
            ),
        ),
    ]
