# Generated by Django 5.2.5 on 2025-09-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_remove_liquidity_id_liquidity_buy_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidity',
            name='in_case',
            field=models.BooleanField(default=True),
        ),
    ]
