# Generated by Django 5.2.5 on 2025-09-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_liquidity_in_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidity',
            name='link',
            field=models.URLField(default='https://getgems.io/'),
        ),
    ]
