# Generated by Django 5.2.5 on 2025-09-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_alter_liquidity_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidity',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='liquidity',
            name='liquidity_id',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='in_stock_count',
        ),
        migrations.AddField(
            model_name='liquidity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
