# Generated by Django 5.2.5 on 2025-09-30 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0006_remove_liquidity_buy_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_data', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('liquidity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packs.liquidity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PackSell',
            },
        ),
    ]
