# Generated by Django 5.2.5 on 2025-10-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0007_packsell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packsell',
            old_name='sell_data',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='packsell',
            name='price',
        ),
    ]
